### ISSUE TITLE
Frame rate

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r2live#10]
Hei guys. 
Looking forward for your work! Any estimations of when will be available? Just asking me a couple of questions. If it is possible, could you please incorporate two things in your code or document where they can be modified
- IMU, Camera and Lidar offset and extrinsic 
- IMU, Camera and Lidar frame rate (i.e. cameras with slower frame rate)

I believe that been able to easily modify these parameters will be the best way to integrate your code in different scenarios.

Thanks!
Ps: If you could incorporate a way to also separate the capturing and the data processing for later post processing with PPK will be awesome too but that is more work ....

**Comment by ziv-lin** [comment]
Our codes are now available. For more about our hardware setup, please refer to our related paper.
