### ISSUE TITLE
Could not find #include <vins_estimator/States.h>

### ISSUE THREAD

**Issue by wwtinwhu** [hku-mars/r2live#12]
and #include <vins_estimator/Pose6D.h>

**Comment by ziv-lin** [comment]
It seems that I have forgotten to add some files that used to generate ros_message header files, let me fix it now.

**Comment by wwtinwhu** [comment]
> It seems that I have forgotten to add some files that used to generate ros_message header files, let me fix it now.

yeah，thx！

**Comment by ziv-lin** [comment]
I have found the problem and commit a hotfix just now, can you try it again?

**Comment by wwtinwhu** [comment]
> I have found the problem and commit a hotfix just now, can you try it again?

So fast！I will try it again tomorrow！Good night.

**Comment by wwtinwhu** [comment]
> I have found the problem and commit a hotfix just now, can you try it again?

It works! Good Work!
![Uploading 截图_2021-06-22_09-30-18.png…]()
