### ISSUE TITLE
Hardware info request

### ISSUE THREAD

**Issue by vipelz** [hku-mars/r2live#18]
Hi guys what a great work!
Could you please give us more accurate information about the hardware used?
Especially 
- lidar type, 
-  camera,  
- PC specs 
- other sensors(?).
I own a Livox mid 70 which works well with close objects and would like to know if it is supported or when / how it could be.

Thank you!

**Comment by seajayshore** [comment]
Most of this information is available in their research paper which you can find in the "paper" directory in the repository. Refer to section "VI. Experiments and Results" on page 5.

They also give more details, including the camera, here: https://github.com/hku-mars/r2live/issues/6
