### ISSUE TITLE
use with velodyne 16 issue

### ISSUE THREAD

**Issue by sihanh** [hku-mars/r2live#20]
when I use Velodyne 16, switch lidar type to 2, the feature extract node has the following warning.

> Failed to find match for field 'normal_x'.
> Failed to find match for field 'normal_y'.
> Failed to find match for field 'normal_z'.
> Failed to find match for field 'curvature'.

I don't think the velodyne_points field has those attributes and I cannot find in the source code of this warning.

**Comment by ziv-lin** [comment]
Eh, I have not tested my algorithm on Velodyne-16 yet and therefore I do not promise it can work well with it. Maybe you can try to modify the code of LiDAR feature extraction and LIO subsystem to make it capable work with Velodyne LiDARs.

**Comment by satyajitghana** [comment]
@ziv-lin 

Hi, i can see that FAST_LIO supports VELO16, below is the code, where `normal_x,` `normal_y`, `normal_z` and curvature values are there.

https://github.com/hku-mars/FAST_LIO/blob/669eedfc7df1f64413b84adaef96e54b6747e169/src/preprocess.cpp#L317-L326

So do i have to just upgrade the FAST_LIO version in this repository to make it work?

**Comment by CanCanZeng** [comment]
Hi @satyajitghana  @sihanh , do you eventually get it work with vlp16?
