### ISSUE TITLE
What monitor do you use on the handheld capture device?

### ISSUE THREAD

**Issue by seajayshore** [hku-mars/r2live#21]
We see a nice touch screen monitor in your sample video [here](https://www.youtube.com/watch?v=9lqRHmlN_MA) - what device is this? Something from DJI?

**Comment by ziv-lin** [comment]
Our screen is purposed from Taobao, here is the link:
https://detail.tmall.com/item.htm?id=586679765026&spm=a1z09.2.0.0.204f2e8dolgT7F&_u=mrntq1l99a4
