### ISSUE TITLE
How to run on realsense L515?

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/r2live#22]
Thanks for sharing such amazing work. I saw the hardware requirements it needs IMU, Lidar, and RGB data. As per my knowledge all these things are available in realsense L515. Is there any way I can the project with bag file of l515?

Thank you

**Comment by ziv-lin** [comment]
You can use the real-senses config file of VINS-Repo:
https://github.com/HKUST-Aerial-Robotics/VINS-Mono/blob/master/config/realsense/realsense_color_config.yaml
However, to achieve the best performance of point cloud undistortion, we suggest you use the LiDAR build-in IMU (with LiDAR-IMU time synchronization) and with the global shutter camera (IR camera) of Realsense. In this case, you need to enable the online extrinsic IMU-Camera calibration function by modifying the YAML files.
