### ISSUE TITLE
some files missing?

### ISSUE THREAD

**Issue by rahulsharma11** [hku-mars/r2live#24]
Hi,
while compiling r2live, there are few files missing error-
fatal error: r2live/States.h: No such file or directory
and
fatal error: r2live/Pose6D.h: No such file or directory

Any suggestions?
Thanks.

**Comment by rahulsharma11** [comment]
It was related to c++ standards.
Thanks

**Comment by jinzhenmu** [comment]
> It was related to c++ standards.
> Thanks

hi  i meet this problem too, and  how to solve?

**Comment by rahulsharma11** [comment]
If you are using opencv>3 then check for c++14 in CMakeList.txt
Also you can try to build with full throttle and the above files will automatically generated...Try to make 3-4 times catkin_make
