### ISSUE TITLE
typo in equ(16) ?

### ISSUE THREAD

**Issue by narutojxl** [hku-mars/r2live#3]
Hi authors,
Thanks for your hard-core paper and sharing your knowledge very very much! Is there a typo in equ(16) ? Thanks for your help and time very much!
![image](https://user-images.githubusercontent.com/6205343/112956032-9d857300-9172-11eb-979c-9fa28baa031a.png)
![image](https://user-images.githubusercontent.com/6205343/112955230-cbb68300-9171-11eb-9fd5-e9771b0d9480.png)

**Comment by ziv-lin** [comment]
Yes,  we have found this error in our paper. We make some mistakes in
"copying" formulation in the codes to our paper. We will correct this
mistake in the next version of the paper...


Xiaoliang Jiao ***@***.***> 于2021年3月30日周二 下午4:34写道：

**Comment by narutojxl** [comment]
OK, thanks author, my problem is solved, close it now.
