### ISSUE TITLE
will it update to use fast-lio2?

### ISSUE THREAD

**Issue by CanCanZeng** [hku-mars/r2live#34]
Hi @ziv-lin , thanks for sharing your great work!
The fast-lio2 has been released, it's more precise and robust, and can be applied to both solid-state  and mechanical lidar. Will you update the lidar odometry to fast-lio2?

**Comment by ziv-lin** [comment]
I am developing the next version of R2LIVE, which will support more types of LiDARs, and is more fast, robust, and accurate than the current version. It will be released in the coming months.

**Comment by CanCanZeng** [comment]
Wow, what an exciting news! We are looking forward to it
