### ISSUE TITLE
Fδx and Fw derivation

### ISSUE THREAD

**Issue by narutojxl** [hku-mars/r2live#4]
Hi author,
I'm curious about Fδx and Fw derivation in Supplementary Material B. There are some question want to ask for your help, hope this will not make you annoyed and angry. Thanks for your help and time a lot! 
This is the [whole derivation process](https://drive.google.com/file/d/16R9QklzXCUWFqVVgJMIQLZWr3jD4PQMV/view?usp=sharing) about `delta_x{i+1}_hat`, namely equ(6) of paper and `Fδx and Fw`, i am not sure whether there is some wrong place, if anybody find it, please give a comment, thanks for author's wonderful work!
* In the following picture, the delta_* variables in time i instant, is with hat ? 
![g_1](https://user-images.githubusercontent.com/6205343/113163544-da389380-9272-11eb-9491-faf1b2148ef2.png)

* When deriving rotaion part, compare with paper's result, there are some differences, i'm not sure whether it is a typo or i am wrong.
 right jacobian does not transpose and is multiplied with delta_t.
![image](https://user-images.githubusercontent.com/6205343/113119099-a5144d00-9242-11eb-9a1b-09c928a9fec1.png)

![606487cf13601239ef000006](https://user-images.githubusercontent.com/6205343/113273662-7617dd00-930f-11eb-916b-c8415db87791.png)

![2021-04-01 15-37-17屏幕截图](https://user-images.githubusercontent.com/6205343/113273419-34873200-930f-11eb-888b-aeabcc1de8dd.png)

* When deriving translation part, there seems not exist `0.5*(a_i - a_i_hat)*delta_t*delta_t`
* The velocity result mach with paper's result, this is the derivation.
![image](https://user-images.githubusercontent.com/6205343/113124838-87e27d00-9248-11eb-8eec-3957a00a7b16.png)
![image](https://user-images.githubusercontent.com/6205343/113124343-ff63dc80-9247-11eb-916a-1674dff58953.png)

**Comment by ziv-lin** [comment]
Let me check them again, we also found some other errors in our paper and we will correct them in the next version of this paper.
Anyway, thank you for your correction.

**Comment by narutojxl** [comment]
Thanks author, Indeed, the above all equations depends on the correct equ(6) of paper, we need very carefully derive it. I will follow author's idea to see whether i can get the same result with paper's result of equ(6). Thanks again!
![image](https://user-images.githubusercontent.com/6205343/113145337-e3b90000-9260-11eb-9927-8e6b5b8539ca.png)

**Comment by ziv-lin** [comment]
Yes, you are right, we need to careful in deriving such formulations. Actually speaking, we started to write this paper one week before DDL. It is unavoidable for us in making mistakes (e.g. typos and errors in derivations) in this version of preprint paper. 
I will upload an amendation version of this paper this week to this GitHub page.
Again, thank you for your corrections~
