### ISSUE TITLE
Drift in running r2live.

### ISSUE THREAD

**Issue by rahulsharma11** [hku-mars/r2live#40]
Hi,
i am using livox avia with IDS global shutter camera.
I have calibrated camera and livox-camera as well through this-
https://github.com/hku-mars/livox_camera_calib
Checked the optimizer result and it was good overlaying.

Using the livox-ros-driver -
https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE

Run commands-
1) roslaunch r2live demo.launch (updated demo.launch with updated config.yaml)
2) roslaunch livox_ros_driver livox_lidar_msg.launch (To publish livox message)

As soon it started, it continously drift and goes along like a pipe. Not giving the results.

**Note-
i got extrinsic after livox-camera-calibration, and did -
rotation = r^(-1), translation = -r^(-1) * t, where r, t is the origin rotation and translation in result/extrinsic.txt. As i found 
Rotation from camera frame to imu frame, imu^R_cam and Translation from camera frame to imu frame, imu^T_cam.**

Any suggestions to check ? like parameters or something else.

Thanks.

**Comment by Camilochiang** [comment]
Hei @rahulsharma11  did you solve this issue? I assume that the problem is that R2live require the matrix for the IMU and the camera , meanwhiles you calculate the IMU and the LiDAR. Still, not sure if it justify the constant drifting....
