### ISSUE TITLE
DSLR camera

### ISSUE THREAD

**Issue by antun008** [hku-mars/r2live#44]
Can I use a simple DSLR Camera? If not, why do we need to use this industrial camera that has not many megapixels? sry for stupid question:)

**Comment by Camilochiang** [comment]
Basically a DSLR camera is neither fast enough for this work (10-30 hz )nor  have fix parameters (focus, view angle, etc), what is need it to keep the data fusion between the lidar and the camera. For this you want to use a "pinhole camera" that is fast enough :)

Ps: There are no stupid questions. We are all learning.
Ps2: If this answer your question, is a good practice to close the "issue"
