### ISSUE TITLE
bad map result 

### ISSUE THREAD

**Issue by huangsiyuan0717** [hku-mars/r2live#47]
Thanks for your great job!
I use your data, but don't get your result, what can i do to get better result?

![Screenshot from 2021-09-13 20-05-57](https://user-images.githubusercontent.com/69231540/133085426-f1e36b81-0427-40bf-98ae-794e8ba9e366.png)

**Comment by ziv-lin** [comment]
What is your hardware platform (cpu and RAM) and software environment ( opencv, pcl, eigen, and etc )?

**Comment by huangsiyuan0717** [comment]
> What is your hardware platform (cpu and RAM) and software environment ( opencv, pcl, eigen, and etc )?
Thanks for your reply, my hardware and software environment as the follows:
cpu: Intel® Core™ i5-10400 
RAM: 16G
eigen: 3.3.4
opencv: 3.4.0
pcl: 1.8.1

**Comment by huangsiyuan0717** [comment]
> What is your hardware platform (cpu and RAM) and software environment ( opencv, pcl, eigen, and etc )?

Thanks for your reply, my hardware and software environment as the follows:
cpu: Intel® Core™ i5-10400 
RAM: 16G
eigen: 3.3.4
opencv: 3.4.0
pcl: 1.8.1

**Comment by huangsiyuan0717** [comment]
> What is your hardware platform (cpu and RAM) and software environment ( opencv, pcl, eigen, and etc )?

This issue was closed due to my wrong operation, I open it again.

**Comment by ziv-lin** [comment]
It seems that your environment is OK, is every time you always get the wrong results? i.e. you run the same example five times and the map is drifted each time.

**Comment by huangsiyuan0717** [comment]
> It seems that your environment is OK, is every time you always get the wrong results? i.e. you run the same example five times and the map is drifted each time.

Yes，I got the same result after three times.
And there are some error as the follows:
![Screenshot from 2021-09-15 15-26-56](https://user-images.githubusercontent.com/69231540/133390078-4dc4ca47-8e00-48b3-aa1a-498cf284dbb3.png)
![Screenshot from 2021-09-15 15-27-35](https://user-images.githubusercontent.com/69231540/133390084-94d5dd13-8886-4751-8b7c-f36efb7d0ec8.png)

**Comment by ziv-lin** [comment]
Is the other 2 bags run normally?

**Comment by ziv-lin** [comment]
Notice that your RAM is only 16Gb, and you are running this bag with rViz displaying all the points, which will take up too much memory. 
Can you use the system monitor to monitor the use of memory when you're running this bag? 
Type this command on your terminal to open the monitor:
```
gnome-system-monitor
```

**Comment by ziv-lin** [comment]
Maybe your problem is caused by loss of data due to the limited available memory.
