### ISSUE TITLE
R2Live + external IMU

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r2live#48]
Good day!
I have a running environment with FAST-LIO2 using an external IMU, thanks for that!
 Would be possible in the future to use an external IMU also with r2live? will be great for MID40 and MID70.

Thanks.

**Comment by ziv-lin** [comment]
I am sorry that I can not answer your question since I haven't try to use an external IMU yet.

**Comment by Camilochiang** [comment]
Easy. I could share you a rosbag if you would like ;) (IMU + MID70 + Camera)

**Comment by zgxsin** [comment]
I am trying to run R2live with an external IMU. I will update here. 

1. Could you confirm the the IMU and LIDAR frame have identity rotation among them in the livox device you have used?

2. And the translation is hard-coded here: https://github.com/hku-mars/r2live/blob/master/r2live/src/fast_lio/include/common_lib.h#L58?

3. If my IMU has a rotation to my LIDAR frame, i have to change it here: https://github.com/hku-mars/r2live/blob/master/r2live/src/fast_lio/fast_lio.hpp#L208:

  from 
  ```
  Eigen::Vector3d p_global(g_lio_state.rot_end * (p_body + Lidar_offset_to_IMU) + g_lio_state.pos_end);
  ```
  to
  ```
  Eigen::Vector3d p_global(g_lio_state.rot_end * (R_Lidar_to_IMU*p_body + Lidar_offset_to_IMU) + g_lio_state.pos_end);
  ```

**Comment by Camilochiang** [comment]
Hei @zgxsin Did you succed? Just curious.

**Comment by zuowei1998** [comment]
Hello, @zgxsin Did you succed? my device is robosense16 and mpu6050

**Comment by Sunny-cpp** [comment]
> 

I also have the mid-70 and want to run R2Live by using it.
could you share your hardware scheme and rosbag?
thank you!

**Comment by Sunny-cpp** [comment]
> Easy. I could share you a rosbag if you would like ;) (IMU + MID70 + Camera)

I also have the mid-70 and want to run R2Live by using it.
could you share your hardware scheme and rosbag?
thank you!
