### ISSUE TITLE
Save Lidar or camara trajectory

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r2live#55]
As in Fast_lio2 , Is there a way to save the trajectory of the camera/lidar?  Thanks!

**Comment by Camilochiang** [comment]
I assume that /path correspond to the topic with the coordinates . Is with reference to the LIDAR or the IMU?

**Comment by Camilochiang** [comment]
I Didn't find a direct way, so at the end I add another node that grab all the pcl output from /cloud_register and /path to save a pcd with all data and a txt with the positions.

**Comment by hr2894235132** [comment]
hello,can you teach me how to get a txt with the positions?please,thanks!

**Comment by ly-uuu** [comment]
Hello Camilochiang
can you tell me how to get a txt with the positions?thanks!
