### ISSUE TITLE
how to align pointcloud map to real picture

### ISSUE THREAD

**Issue by huangsiyuan0717** [hku-mars/r2live#59]
![Screenshot from 2021-11-11 18-37-23](https://user-images.githubusercontent.com/69231540/141283871-b528e3a7-7ed7-42f7-911b-e4f7f43a85ba.png)
Hi! How did you align the map? And the real map how do you get(google earth?)? 
I want to display the real data use this way with pointcloud map, but I don't konw how to align it .

**Comment by ziv-lin** [comment]
I use photoshop to align the maps, with just scaling the point cloud image.

**Comment by ccq0905** [comment]
> ![Screenshot from 2021-11-11 18-37-23](https://user-images.githubusercontent.com/69231540/141283871-b528e3a7-7ed7-42f7-911b-e4f7f43a85ba.png) Hi! How did you align the map? And the real map how do you get(google earth?)? I want to display the real data use this way with pointcloud map, but I don't konw how to align it .

How do you get pointcloud map, could you share with me?
