### ISSUE TITLE
lio_feat_extract died when using Livox Mid-70

### ISSUE THREAD

**Issue by yuhang1008** [hku-mars/r2live#63]
Dear developers, thanks for your amazing work on this multi sensor algorithm.

I'm currently trying to run R2live on my devices, they are Livox Mid-70, Zed2i(camera and built-in IMU). I've customized the filr_cam.yaml to adapt my device, and rename the topics to the same provided in you rosbag. When play my own recorded rosbag. The camera part and imu data have been successfully connected.
![Screenshot from 2021-12-17 12-43-42](https://user-images.githubusercontent.com/69785712/146490553-9674080f-bd0c-4bec-be81-7831c9e3de49.png)

but my lidar data can not be linked.
![Screenshot from 2021-12-17 12-44-01](https://user-images.githubusercontent.com/69785712/146490585-c36bc8fe-2560-461e-b9e0-afeefa11a256.png)

It shows this error in terminal:
![Screenshot from 2021-12-16 19-47-17](https://user-images.githubusercontent.com/69785712/146490679-d3a16fab-5cbe-490d-b365-0fb8fd6ca2d7.png)

I check the log file but it's a blank file. So far I have no idea how to connect my lidar(mid-70) data. Could you help me with this problem? Thanks in advance!

**Comment by Camilochiang** [comment]
1. This repo is not even in use as the authors are working in the new version 
2. You dont even see the lidar in the node graph, therefore I will asume that is not been detected/you have bigger issue not related to r2live. Did you install livox ros driver as indicated in the instructions?

**Comment by cnhanyuhang** [comment]
Thank you for prompt reply. I think it may not be the driver issue because I have recorded /livox/lidar topic in my rosbag and it can be used in loam-livox. Let me recheck my bag and do more tests, then I may update later. Anyway, thank you.


Best regards,
Han Yuhang

-----------------------
Han Yuhang
Master of Science
School of Mechanical Engineering,
National University of Singapore （NUS）

***@***.***
(65)80387345

________________________________

**Comment by yuhang1008** [comment]
> 1. This repo is not even in use as the authors are working in the new version
> 2. You dont even see the lidar in the node graph, therefore I will asume that is not been detected/you have bigger issue not related to r2live. Did you install livox ros driver as indicated in the instructions?

Thank you for prompt reply. I think it may not be the driver issue because I have recorded /livox/lidar topic in my rosbag and it can be used in loam-livox. Let me recheck my bag and do more tests, then I may update later. Anyway, thank you.

**Comment by ziv-lin** [comment]
If the ros message can be used in loam-livox, that means you are recording the pointcloud data in PCL/pointcloud2. However, in R2LIVE and R3LIVE (coming soon), we use the Livox custom message, in which the datatype has recorded the timestamp of each point (used for point cloud motion compensation).

**Comment by yuhang1008** [comment]
> If the ros message can be used in loam-livox, that means you are recording the pointcloud data in PCL/pointcloud2. However, in R2LIVE and R3LIVE (coming soon), we use the Livox custom message, in which the datatype has recorded the timestamp of each point (used for point cloud motion compensation).

Thanks for your reply, let me record the livox custom msg and try again. Looking forward to r3live!
