### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by ccq0905** [hku-mars/r2live#68]
When I run it by my Lidar(Avia) and camera（FLIR），I modfied the config flir_cam.yaml, but it occurs!!!
![problem](https://user-images.githubusercontent.com/104149220/167608679-8efc9bf7-1b9e-4c95-9672-8f532002cb29.png)

**Comment by lhthq** [comment]
hi~  I  also  have this error!   Do you have any ideas? THANK YOU!

**Comment by ccq0905** [comment]
> hi~ I also have this error! Do you have any ideas? THANK YOU!

No. I couldn't solve it, so I really someone could help me.

**Comment by pangchenglin** [comment]
hi~ I also have this error! Did you have solved this problem？
