### ISSUE TITLE
launch error: doesn't exist

### ISSUE THREAD

**Issue by Hjw-Edward** [hku-mars/r2live#69]
Hello! Could I ask you how to deal with the problem ? It is worth mentioning that I verify my software environment.
My software version are listed as follow:
My OpenCV Version is: 3.3.1
My ceres version is: 1.14.0
My Eigen version is: 3.3.9

when I roslaunch r2live demo.launch,it gives the following error:
... logging to /home/hjw/.ros/log/8da4a8f8-eb89-11ec-ab9e-f02f74f50fd8/roslaunch-hjw-pc-5650.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://hjw-pc:45045/

SUMMARY
========

PARAMETERS
 * /acc_mul_G: 0
 * /fast_lio/cube_side_length: 1000000000
 * /fast_lio/dense_map_enable: True
 * /fast_lio/filter_size_corner: 0.4
 * /fast_lio/filter_size_map: 0.4
 * /fast_lio/filter_size_surf: 0.4
 * /fast_lio/filter_size_surf_z: 0.4
 * /fast_lio/fov_degree: 360.0
 * /fast_lio/local_loop_win: [110, -116, 155, ...
 * /fast_lio/m_long_rang_pt_dis: 500
 * /fast_lio/map_file_path:  
 * /fast_lio/max_iteration: 4
 * /fast_lio/maximum_pt_kdtree_dis: 0.5
 * /fast_lio/maximum_res_dis: 0.3
 * /fast_lio/planar_check_dis: 0.1
 * /fast_lio/publish_feature_map: False
 * /feature_extraction/N_SCANS: 6
 * /feature_extraction/blind: 0.1
 * /feature_extraction/cos160: 160.0
 * /feature_extraction/disA: 0.01
 * /feature_extraction/disB: 0.1
 * /feature_extraction/edgea: 2
 * /feature_extraction/edgeb: 0.1
 * /feature_extraction/group_size: 8
 * /feature_extraction/inf_bound: 4
 * /feature_extraction/jump_down_limit: 8.0
 * /feature_extraction/jump_up_limit: 170.0
 * /feature_extraction/lidar_type: 1
 * /feature_extraction/limit_maxmid: 6.25
 * /feature_extraction/limit_maxmin: 3.24
 * /feature_extraction/limit_midmin: 6.25
 * /feature_extraction/p2l_ratio: 225
 * /feature_extraction/point_filter_num: 1
 * /feature_extraction/point_step: 3
 * /feature_extraction/smallp_intersect: 172.5
 * /feature_extraction/smallp_ratio: 1.2
 * /feature_extraction/using_raw_point: 1
 * /feature_tracker/config_file: /home/hjw/catkin_...
 * /feature_tracker/image_topic: /camera/image_color
 * /feature_tracker/vins_folder: /home/hjw/catkin_...
 * /if_dump_log: 0
 * /if_lidar_start_first: 1
 * /if_write_to_bag: 0
 * /imu_topic: /livox/imu
 * /lidar_drag_cam_tim: 10
 * /r2live/config_file: /home/hjw/catkin_...
 * /r2live/vins_folder: /home/hjw/catkin_...
 * /record_bag_name: /home/ziv/kitti_b...
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    feature_tracker (feature_tracker/feature_tracker)
    lio_feat_extract (r2live/lio_feat_extract)
    r2live (r2live/r2live)
    rvizvisualisation (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[feature_tracker-1]: started with pid [5680]
process[lio_feat_extract-2]: started with pid [5681]
process[r2live-3]: started with pid [5682]
process[rvizvisualisation-4]: started with pid [5688]
[ INFO] [1655173755.828430334]: init begins
[ INFO] [1655173755.831679860]: Loaded config_file: /home/hjw/catkin_ws/src/r2live/r2live/../config/filr_cam.yaml
result path /vins_result_no_loop.csv
 not exists, trying to create it 
Failed to create folder  
[ INFO] [1655173755.832502542]: ROW: 512.000000 COL: 640.000000 
[ WARN] [1655173755.832544487]:  fix extrinsic param 
[ INFO] [1655173755.832787727]: Extrinsic_R : 
  0.00193065   -0.0166655     0.999859
   -0.999998  0.000312504   0.00193612
-0.000344726    -0.999861   -0.0166649
[ INFO] [1655173755.832907185]: Extrinsic_T : 
 0.03056  0.06429 -0.00865
[ INFO] [1655173755.832969301]: Unsynchronized sensors, online estimate time offset, initial td: 0
[Ros_parameter]: /lidar_drag_cam_tim ==> 10
[Ros_parameter]: /acc_mul_G ==> 0
[Ros_parameter]: /if_lidar_start_first ==> 1
[Ros_parameter]: /if_write_to_bag ==> 0
[Ros_parameter]: /if_dump_log ==> 0
[Ros_parameter]: /record_bag_name ==> /home/ziv/kitti_bag/lic_record_bag/lic.bag
Multi thread started 
/home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 786
[Ros_parameter]: fast_lio/dense_map_enable ==> 1
[Ros_parameter]: fast_lio/lidar_time_delay ==> 0
[Ros_parameter]: fast_lio/max_iteration ==> 4
[Ros_parameter]: fast_lio/fov_degree ==> 360
[Ros_parameter]: fast_lio/filter_size_corner ==> 0.4
[Ros_parameter]: fast_lio/filter_size_surf ==> 0.4
[Ros_parameter]: fast_lio/filter_size_surf_z ==> 0.4
[Ros_parameter]: fast_lio/filter_size_map ==> 0.4
[Ros_parameter]: fast_lio/cube_side_length ==> 1e+09
[Ros_parameter]: fast_lio/maximum_pt_kdtree_dis ==> 0.5
[Ros_parameter]: fast_lio/maximum_res_dis ==> 0.3
[Ros_parameter]: fast_lio/planar_check_dis ==> 0.1
[Ros_parameter]: fast_lio/long_rang_pt_dis ==> 50
[Ros_parameter]: fast_lio/publish_feature_map ==> 0
/home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 811
/home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 824
/home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 826
[ WARN] [1655173755.877137555]: waiting for image and imu...
~~~~/home/hjw/catkin_ws/src/r2live/r2live/ doesn't exist


[r2live-3] process has died [pid 19790, exit code -11, cmd /home/hjw/catkin_ws/devel/lib/r2live/r2live __name:=r2live __log:=/home/hjw/.ros/log/179a6104-eae2-11ec-9b09-f02f74f50fd8/r2live-3.log].
log file: /home/hjw/.ros/log/179a6104-eae2-11ec-9b09-f02f74f50fd8/r2live-3*.log

**Comment by hr2894235132** [comment]
> Hello! Could I ask you how to deal with the problem ? It is worth mentioning that I verify my software environment. My software version are listed as follow: My OpenCV Version is: 3.3.1 My ceres version is: 1.14.0 My Eigen version is: 3.3.9
> 
> when I roslaunch r2live demo.launch,it gives the following error: ... logging to /home/hjw/.ros/log/8da4a8f8-eb89-11ec-ab9e-f02f74f50fd8/roslaunch-hjw-pc-5650.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://hjw-pc:45045/
> 
> # SUMMARY
> PARAMETERS
> 
> * /acc_mul_G: 0
> * /fast_lio/cube_side_length: 1000000000
> * /fast_lio/dense_map_enable: True
> * /fast_lio/filter_size_corner: 0.4
> * /fast_lio/filter_size_map: 0.4
> * /fast_lio/filter_size_surf: 0.4
> * /fast_lio/filter_size_surf_z: 0.4
> * /fast_lio/fov_degree: 360.0
> * /fast_lio/local_loop_win: [110, -116, 155, ...
> * /fast_lio/m_long_rang_pt_dis: 500
> * /fast_lio/map_file_path:
> * /fast_lio/max_iteration: 4
> * /fast_lio/maximum_pt_kdtree_dis: 0.5
> * /fast_lio/maximum_res_dis: 0.3
> * /fast_lio/planar_check_dis: 0.1
> * /fast_lio/publish_feature_map: False
> * /feature_extraction/N_SCANS: 6
> * /feature_extraction/blind: 0.1
> * /feature_extraction/cos160: 160.0
> * /feature_extraction/disA: 0.01
> * /feature_extraction/disB: 0.1
> * /feature_extraction/edgea: 2
> * /feature_extraction/edgeb: 0.1
> * /feature_extraction/group_size: 8
> * /feature_extraction/inf_bound: 4
> * /feature_extraction/jump_down_limit: 8.0
> * /feature_extraction/jump_up_limit: 170.0
> * /feature_extraction/lidar_type: 1
> * /feature_extraction/limit_maxmid: 6.25
> * /feature_extraction/limit_maxmin: 3.24
> * /feature_extraction/limit_midmin: 6.25
> * /feature_extraction/p2l_ratio: 225
> * /feature_extraction/point_filter_num: 1
> * /feature_extraction/point_step: 3
> * /feature_extraction/smallp_intersect: 172.5
> * /feature_extraction/smallp_ratio: 1.2
> * /feature_extraction/using_raw_point: 1
> * /feature_tracker/config_file: /home/hjw/catkin_...
> * /feature_tracker/image_topic: /camera/image_color
> * /feature_tracker/vins_folder: /home/hjw/catkin_...
> * /if_dump_log: 0
> * /if_lidar_start_first: 1
> * /if_write_to_bag: 0
> * /imu_topic: /livox/imu
> * /lidar_drag_cam_tim: 10
> * /r2live/config_file: /home/hjw/catkin_...
> * /r2live/vins_folder: /home/hjw/catkin_...
> * /record_bag_name: /home/ziv/kitti_b...
> * /rosdistro: melodic
> * /rosversion: 1.14.13
> 
> NODES / feature_tracker (feature_tracker/feature_tracker) lio_feat_extract (r2live/lio_feat_extract) r2live (r2live/r2live) rvizvisualisation (rviz/rviz)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[feature_tracker-1]: started with pid [5680] process[lio_feat_extract-2]: started with pid [5681] process[r2live-3]: started with pid [5682] process[rvizvisualisation-4]: started with pid [5688] [ INFO] [1655173755.828430334]: init begins [ INFO] [1655173755.831679860]: Loaded config_file: /home/hjw/catkin_ws/src/r2live/r2live/../config/filr_cam.yaml result path /vins_result_no_loop.csv not exists, trying to create it Failed to create folder [ INFO] [1655173755.832502542]: ROW: 512.000000 COL: 640.000000 [ WARN] [1655173755.832544487]: fix extrinsic param [ INFO] [1655173755.832787727]: Extrinsic_R : 0.00193065 -0.0166655 0.999859 -0.999998 0.000312504 0.00193612 -0.000344726 -0.999861 -0.0166649 [ INFO] [1655173755.832907185]: Extrinsic_T : 0.03056 0.06429 -0.00865 [ INFO] [1655173755.832969301]: Unsynchronized sensors, online estimate time offset, initial td: 0 [Ros_parameter]: /lidar_drag_cam_tim ==> 10 [Ros_parameter]: /acc_mul_G ==> 0 [Ros_parameter]: /if_lidar_start_first ==> 1 [Ros_parameter]: /if_write_to_bag ==> 0 [Ros_parameter]: /if_dump_log ==> 0 [Ros_parameter]: /record_bag_name ==> /home/ziv/kitti_bag/lic_record_bag/lic.bag Multi thread started /home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 786 [Ros_parameter]: fast_lio/dense_map_enable ==> 1 [Ros_parameter]: fast_lio/lidar_time_delay ==> 0 [Ros_parameter]: fast_lio/max_iteration ==> 4 [Ros_parameter]: fast_lio/fov_degree ==> 360 [Ros_parameter]: fast_lio/filter_size_corner ==> 0.4 [Ros_parameter]: fast_lio/filter_size_surf ==> 0.4 [Ros_parameter]: fast_lio/filter_size_surf_z ==> 0.4 [Ros_parameter]: fast_lio/filter_size_map ==> 0.4 [Ros_parameter]: fast_lio/cube_side_length ==> 1e+09 [Ros_parameter]: fast_lio/maximum_pt_kdtree_dis ==> 0.5 [Ros_parameter]: fast_lio/maximum_res_dis ==> 0.3 [Ros_parameter]: fast_lio/planar_check_dis ==> 0.1 [Ros_parameter]: fast_lio/long_rang_pt_dis ==> 50 [Ros_parameter]: fast_lio/publish_feature_map ==> 0 /home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 811 /home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 824 /home/hjw/catkin_ws/src/r2live/r2live/src/./fast_lio/fast_lio.hpp 826 [ WARN] [1655173755.877137555]: waiting for image and imu...
> 
> ```
> 
> 
> [r2live-3] process has died [pid 19790, exit code -11, cmd /home/hjw/catkin_ws/devel/lib/r2live/r2live __name:=r2live __log:=/home/hjw/.ros/log/179a6104-eae2-11ec-9b09-f02f74f50fd8/r2live-3.log].
> log file: /home/hjw/.ros/log/179a6104-eae2-11ec-9b09-f02f74f50fd8/r2live-3*.log
> ```

Hello! I am experiencing the same problem as you, did you solve the problem?
