### ISSUE TITLE
one problem 

### ISSUE THREAD

**Issue by liming-jing** [hku-mars/r2live#74]
![image](https://user-images.githubusercontent.com/58467809/223949572-126f52c7-789c-4fd4-8179-41f650eab27e.png)

After I start demo.launch, the rviz display is normal, but when I play the data, the r2live node dies. I have the above problem on both Ubuntu18.04 and Ubuntu20.04 systems, and I don't know why.

**Comment by leslieburke** [comment]
@liming-jing 我也是一样的问题，请问你解决了吗

**Comment by zhuhongwei123** [comment]
请问解决了吗
