### ISSUE TITLE
Question about formula derivation

### ISSUE THREAD

**Issue by SlamCabbage** [hku-mars/r2live#75]
![e44990d4-cc7f-4cdf-ab9b-12699aa2c35a](https://github.com/hku-mars/r2live/assets/95751923/a66648c9-d3a2-46de-a058-432a42ce8bf7)
这里采用了SO3的伴随性质：
R^T exp(a[x]) R = exp((R^T a)[x])
为什么图中的推导没有加上转置呢？

**Comment by gyubeomim** [comment]
Same question here. Maybe it's a typo
