### ISSUE TITLE
equation error

### ISSUE THREAD

**Issue by Gaoyuhanghaoren** [hku-mars/r2live#9]
![image](https://user-images.githubusercontent.com/34000284/119072401-fc9e9000-ba1d-11eb-89d4-c39b28b4e366.png)
![image](https://user-images.githubusercontent.com/34000284/119072464-150eaa80-ba1e-11eb-99e9-a163b8cc8f12.png)

**Comment by narutojxl** [comment]
yes, it's a typo, see supplementary D part.
